# Generated by Django 6.0.5 on 2026-05-21 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='frequency',
            field=models.CharField(default='Daily', max_length=100),
        ),
        migrations.AddField(
            model_name='habit',
            name='icon',
            field=models.CharField(default='⭐', max_length=50),
        ),
        migrations.AddField(
            model_name='habit',
            name='target',
            field=models.IntegerField(default=30),
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('mood', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challengeId', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=50)),
                ('cat', models.CharField(max_length=100)),
                ('days', models.IntegerField()),
                ('joined', models.BooleanField(default=False)),
                ('prog', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=50)),
                ('bg', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
