# Generated by Django 5.2.15 on 2026-10-06 14:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_habit_frequency_habit_icon_habit_target_journalentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='color',
            field=models.CharField(blank=True, default='#10b981', max_length=50),
        ),
        migrations.AddField(
            model_name='habit',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habit',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='priority',
            field=models.CharField(default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminderEnabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminderTime',
            field=models.CharField(blank=True, default='08:00', max_length=20),
        ),
        migrations.AddField(
            model_name='habit',
            name='scheduledDays',
            field=models.JSONField(blank=True, default=api.models.default_scheduled_days),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='dailyTarget',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='user',
            name='goal',
            field=models.CharField(blank=True, default='🌟 All-round improvement', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=100),
        ),
    ]
